/* automatically generated by locomoto v1.22 (Hide and Seek) - http://www.eac.ea.com/tools/locale/ */

/* Language ID's */
const int 1948 356 No.1                            = 0;
const int                                          = 1;
const int                                          = 2;
const int                                          = 3;
const int                                          = 4;
const int                                          = 5;
const int                                          = 6;

const int LOCALE_LANGUAGE_COUNT                    = 7;


/* string ID's */
const int                                          = 2;
const int                                          = 4;
const int                                          = 6;
const int                                          = 8;
const int                                          = 10;
const int                                          = 12;
const int                                          = 14;
const int                                          = 16;
const int                                          = 18;
const int                                          = 20;
const int                                          = 22;
const int                                          = 24;
const int                                          = 26;
const int                                          = 28;
const int                                          = 30;
const int                                          = 32;
const int                                          = 34;
const int                                          = 36;
const int                                          = 38;
const int                                          = 40;
const int                                          = 42;
const int                                          = 44;
const int                                          = 46;
const int                                          = 48;
const int                                          = 50;
const int                                          = 52;
const int                                          = 54;
const int                                          = 56;
const int                                          = 58;
const int                                          = 60;
const int                                          = 62;
const int                                          = 64;
const int                                          = 66;
const int                                          = 68;
const int                                          = 70;
const int                                          = 72;
const int                                          = 74;
const int                                          = 76;
const int                                          = 78;
const int                                          = 80;
const int                                          = 82;
const int                                          = 84;
const int                                          = 86;
const int                                          = 88;
const int                                          = 90;

const int LOCALE_STRING_COUNT                      = 45;

